import { FaBuilding, FaDoorOpen, FaUserFriends, FaIdBadge, FaVideo, FaExclamationTriangle, FaCity, FaTools, FaMapMarkerAlt, FaShieldAlt, FaDesktop, FaNetworkWired } from 'react-icons/fa';

export const modules = [
  {
    key: 'properties',
    name: 'Properties',
    icon: FaBuilding,
    color: '#0070F2',
    group: 'Security Operations',
    description: 'Managed buildings and facilities',
    columns: ['name', 'city', 'state', 'property_type', 'floors', 'cameras_count', 'access_points', 'status'],
    fields: [
      { name: 'name', label: 'Property Name', type: 'text', required: true },
      { name: 'address', label: 'Address', type: 'text' },
      { name: 'city', label: 'City', type: 'text' },
      { name: 'state', label: 'State', type: 'text' },
      { name: 'property_type', label: 'Type', type: 'select', options: ['Class A Office', 'Class B Office', 'Mixed Use', 'Industrial', 'Retail'] },
      { name: 'floors', label: 'Floors', type: 'number' },
      { name: 'sq_ft', label: 'Square Feet', type: 'number' },
      { name: 'cameras_count', label: 'Cameras', type: 'number' },
      { name: 'access_points', label: 'Access Points', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['Active', 'Under Renovation', 'Inactive'] },
    ],
  },
  {
    key: 'access_events',
    name: 'Access Events',
    icon: FaDoorOpen,
    color: '#00D4AA',
    group: 'Security Operations',
    description: 'Badge swipes and access attempts',
    columns: ['person_name', 'property_name', 'door_name', 'direction', 'status', 'method', 'timestamp'],
    fields: [
      { name: 'property_name', label: 'Property', type: 'text', required: true },
      { name: 'person_name', label: 'Person', type: 'text', required: true },
      { name: 'badge_number', label: 'Badge #', type: 'text' },
      { name: 'door_name', label: 'Door', type: 'text' },
      { name: 'direction', label: 'Direction', type: 'select', options: ['Entry', 'Exit'] },
      { name: 'timestamp', label: 'Timestamp', type: 'datetime-local' },
      { name: 'status', label: 'Status', type: 'select', options: ['Granted', 'Denied'] },
      { name: 'method', label: 'Method', type: 'select', options: ['Proximity Card', 'Smart Card', 'Mobile Credential', 'Key Fob', 'Manual Override'] },
    ],
  },
  {
    key: 'incidents',
    name: 'Incidents',
    icon: FaExclamationTriangle,
    color: '#BB0000',
    group: 'Security Operations',
    description: 'Security incidents and investigations',
    columns: ['incident_number', 'title', 'property_name', 'severity', 'incident_type', 'status', 'reported_by'],
    fields: [
      { name: 'incident_number', label: 'Incident #', type: 'text', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'property_name', label: 'Property', type: 'text' },
      { name: 'severity', label: 'Severity', type: 'select', options: ['Critical', 'High', 'Medium', 'Low'] },
      { name: 'incident_type', label: 'Type', type: 'select', options: ['Unauthorized Access', 'Tailgating', 'Fire Alarm', 'Theft', 'Suspicious Package', 'Equipment Failure', 'Security Breach', 'Vandalism', 'Policy Violation', 'Safety', 'External Threat', 'Environmental', 'Lost Credential'] },
      { name: 'status', label: 'Status', type: 'select', options: ['Open', 'Investigating', 'Monitoring', 'Resolved'] },
      { name: 'reported_by', label: 'Reported By', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'resolution', label: 'Resolution', type: 'textarea' },
    ],
  },
  {
    key: 'zones',
    name: 'Zones',
    icon: FaMapMarkerAlt,
    color: '#6C3483',
    group: 'Security Operations',
    description: 'Security zones and areas',
    columns: ['name', 'property_name', 'floor', 'zone_type', 'access_level', 'cameras_count', 'doors_count', 'alarm_enabled'],
    fields: [
      { name: 'name', label: 'Zone Name', type: 'text', required: true },
      { name: 'property_name', label: 'Property', type: 'text' },
      { name: 'floor', label: 'Floor', type: 'text' },
      { name: 'zone_type', label: 'Zone Type', type: 'select', options: ['Lobby', 'Garage', 'Executive', 'Data Center', 'Loading', 'Public Area', 'Trading', 'Laboratory', 'Stairwell', 'Roof', 'Common Area', 'Command Center', 'Amenity'] },
      { name: 'access_level', label: 'Access Level', type: 'select', options: ['Public', 'Tenant', 'Authorized', 'Restricted', 'Executive'] },
      { name: 'cameras_count', label: 'Cameras', type: 'number' },
      { name: 'doors_count', label: 'Doors', type: 'number' },
      { name: 'max_occupancy', label: 'Max Occupancy', type: 'number' },
      { name: 'alarm_enabled', label: 'Alarm Enabled', type: 'select', options: ['true', 'false'] },
    ],
  },
  {
    key: 'guards',
    name: 'Guards',
    icon: FaShieldAlt,
    color: '#1B6B93',
    group: 'Personnel',
    description: 'Security guard roster and shifts',
    columns: ['full_name', 'badge_id', 'property_name', 'shift', 'status', 'certifications'],
    fields: [
      { name: 'full_name', label: 'Full Name', type: 'text', required: true },
      { name: 'badge_id', label: 'Badge ID', type: 'text' },
      { name: 'property_name', label: 'Property', type: 'text' },
      { name: 'shift', label: 'Shift', type: 'select', options: ['Day', 'Swing', 'Night'] },
      { name: 'shift_start', label: 'Shift Start', type: 'time' },
      { name: 'shift_end', label: 'Shift End', type: 'time' },
      { name: 'certifications', label: 'Certifications', type: 'text' },
      { name: 'status', label: 'Status', type: 'select', options: ['On Duty', 'Off Duty', 'On Leave'] },
      { name: 'phone', label: 'Phone', type: 'text' },
    ],
  },
  {
    key: 'visitors',
    name: 'Visitors',
    icon: FaUserFriends,
    color: '#E76500',
    group: 'Personnel',
    description: 'Visitor management and tracking',
    columns: ['visitor_name', 'visitor_company', 'host_name', 'property_name', 'purpose', 'status', 'photo_id_verified'],
    fields: [
      { name: 'visitor_name', label: 'Visitor Name', type: 'text', required: true },
      { name: 'visitor_company', label: 'Company', type: 'text' },
      { name: 'host_name', label: 'Host', type: 'text' },
      { name: 'property_name', label: 'Property', type: 'text' },
      { name: 'check_in', label: 'Check In', type: 'datetime-local' },
      { name: 'check_out', label: 'Check Out', type: 'datetime-local' },
      { name: 'purpose', label: 'Purpose', type: 'select', options: ['Vendor Meeting', 'Audit', 'Server Maintenance', 'Job Interview', 'Package Delivery', 'Property Inspection', 'Client Meeting', 'Financial Audit', 'HVAC Maintenance', 'Lease Negotiation', 'Tech Integration', 'Facility Audit', 'Fire System Inspection', 'Strategy Consult', 'Partnership Meeting', 'Compliance Review'] },
      { name: 'status', label: 'Status', type: 'select', options: ['Pre-Registered', 'Checked In', 'Checked Out'] },
      { name: 'photo_id_verified', label: 'Photo ID Verified', type: 'select', options: ['true', 'false'] },
    ],
  },
  {
    key: 'credentials',
    name: 'Credentials',
    icon: FaIdBadge,
    color: '#107E3E',
    group: 'Personnel',
    description: 'Access badges and credentials',
    columns: ['holder_name', 'badge_number', 'credential_type', 'property_name', 'access_level', 'department', 'status'],
    fields: [
      { name: 'holder_name', label: 'Holder Name', type: 'text', required: true },
      { name: 'badge_number', label: 'Badge #', type: 'text' },
      { name: 'credential_type', label: 'Type', type: 'select', options: ['Proximity Card', 'Smart Card', 'Mobile Credential', 'Key Fob'] },
      { name: 'property_name', label: 'Property', type: 'text' },
      { name: 'access_level', label: 'Access Level', type: 'select', options: ['Full Access', 'Executive', 'Standard', 'Limited', 'Security'] },
      { name: 'department', label: 'Department', type: 'text' },
      { name: 'status', label: 'Status', type: 'select', options: ['Active', 'Suspended', 'Expired', 'Revoked'] },
      { name: 'expiry_date', label: 'Expiry Date', type: 'date' },
    ],
  },
  {
    key: 'cameras',
    name: 'Cameras',
    icon: FaVideo,
    color: '#0854A0',
    group: 'Infrastructure',
    description: 'Surveillance camera systems',
    columns: ['name', 'property_name', 'location_description', 'camera_type', 'status', 'resolution', 'recording_mode'],
    fields: [
      { name: 'name', label: 'Camera Name', type: 'text', required: true },
      { name: 'property_name', label: 'Property', type: 'text' },
      { name: 'location_description', label: 'Location', type: 'text' },
      { name: 'camera_type', label: 'Type', type: 'select', options: ['Dome', 'Bullet', 'PTZ', 'Fisheye', 'Thermal'] },
      { name: 'status', label: 'Status', type: 'select', options: ['Online', 'Offline', 'Maintenance'] },
      { name: 'resolution', label: 'Resolution', type: 'select', options: ['4K', '1080p', '720p'] },
      { name: 'recording_mode', label: 'Recording', type: 'select', options: ['Continuous', 'Motion-Activated', 'Scheduled'] },
    ],
  },
  {
    key: 'work_orders',
    name: 'Work Orders',
    icon: FaTools,
    color: '#DF6E0C',
    group: 'Infrastructure',
    description: 'Maintenance and repair tickets',
    columns: ['work_order_number', 'title', 'property_name', 'device_type', 'priority', 'status', 'assigned_to'],
    fields: [
      { name: 'work_order_number', label: 'WO #', type: 'text', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'property_name', label: 'Property', type: 'text' },
      { name: 'device_type', label: 'Device Type', type: 'select', options: ['Camera', 'Access Reader', 'Door Controller', 'Alarm Panel', 'Intercom', 'NVR', 'Smoke Detector', 'Turnstile', 'Biometric Reader', 'Fence Sensor', 'Emergency Phone'] },
      { name: 'device_name', label: 'Device Name', type: 'text' },
      { name: 'priority', label: 'Priority', type: 'select', options: ['Critical', 'High', 'Medium', 'Low'] },
      { name: 'status', label: 'Status', type: 'select', options: ['Open', 'Scheduled', 'In Progress', 'Completed'] },
      { name: 'assigned_to', label: 'Assigned To', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    key: 'tenants',
    name: 'Tenants',
    icon: FaCity,
    color: '#354A5F',
    group: 'Property Management',
    description: 'Building tenants and leases',
    columns: ['company_name', 'property_name', 'floor', 'suite', 'primary_contact', 'employee_count', 'badge_count', 'access_hours'],
    fields: [
      { name: 'company_name', label: 'Company', type: 'text', required: true },
      { name: 'property_name', label: 'Property', type: 'text' },
      { name: 'floor', label: 'Floor(s)', type: 'text' },
      { name: 'suite', label: 'Suite', type: 'text' },
      { name: 'primary_contact', label: 'Primary Contact', type: 'text' },
      { name: 'employee_count', label: 'Employees', type: 'number' },
      { name: 'badge_count', label: 'Badges', type: 'number' },
      { name: 'lease_end', label: 'Lease End', type: 'date' },
      { name: 'access_hours', label: 'Access Hours', type: 'text' },
    ],
  },
  {
    key: 'device_events',
    name: 'Device Events',
    icon: FaDesktop,
    color: '#BB0000',
    group: 'Real-Time',
    description: 'Live device event log from simulator and webhooks',
    columns: ['event_type', 'device_type', 'device_name', 'property_name', 'severity', 'description', 'created_at'],
    fields: [
      { name: 'event_type', label: 'Event Type', type: 'select', options: ['access_granted', 'access_denied', 'camera_motion', 'sensor_triggered', 'device_offline', 'device_online', 'alarm_triggered', 'alarm_cleared', 'health_warning', 'tailgating_detected'] },
      { name: 'device_type', label: 'Device Type', type: 'select', options: ['Camera', 'Reader', 'Controller', 'Sensor', 'Alarm Panel', 'Network Switch'] },
      { name: 'device_name', label: 'Device Name', type: 'text', required: true },
      { name: 'property_name', label: 'Property', type: 'text', required: true },
      { name: 'zone_name', label: 'Zone', type: 'text' },
      { name: 'severity', label: 'Severity', type: 'select', options: ['info', 'warning', 'critical'] },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    key: 'devices',
    name: 'Device Registry',
    icon: FaNetworkWired,
    color: '#0854A0',
    group: 'Infrastructure',
    description: 'Network device registry with IP management, health monitoring, and commands',
    columns: ['name', 'device_type', 'ip_address', 'manufacturer', 'model', 'property_name', 'status', 'last_seen'],
    fields: [
      { name: 'name', label: 'Device Name', type: 'text', required: true },
      { name: 'device_type', label: 'Device Type', type: 'select', options: ['Camera', 'Reader', 'Controller', 'Sensor', 'Alarm Panel', 'Network Switch'], required: true },
      { name: 'ip_address', label: 'IP Address', type: 'text', required: true },
      { name: 'mac_address', label: 'MAC Address', type: 'text', required: true },
      { name: 'firmware_version', label: 'Firmware Version', type: 'text' },
      { name: 'manufacturer', label: 'Manufacturer', type: 'text' },
      { name: 'model', label: 'Model', type: 'text' },
      { name: 'property_name', label: 'Property', type: 'text' },
      { name: 'zone_name', label: 'Zone', type: 'text' },
      { name: 'subnet', label: 'Subnet', type: 'text' },
      { name: 'port', label: 'Port', type: 'number' },
      { name: 'protocol', label: 'Protocol', type: 'select', options: ['HTTPS', 'HTTP', 'SNMP', 'MQTT'] },
      { name: 'status', label: 'Status', type: 'select', options: ['Online', 'Offline', 'Maintenance', 'Unregistered'] },
    ],
  },
];

export const moduleGroups = [
  { name: 'Security Operations', keys: ['properties', 'access_events', 'incidents', 'zones'] },
  { name: 'Personnel', keys: ['guards', 'visitors', 'credentials'] },
  { name: 'Infrastructure', keys: ['cameras', 'work_orders', 'devices'] },
  { name: 'Property Management', keys: ['tenants'] },
  { name: 'Real-Time', keys: ['device_events'] },
];

export function getModule(key) {
  return modules.find(m => m.key === key);
}

export const aiFeatures = [
  { key: 'soc-copilot', name: 'SOC Copilot', description: 'Chat with an AI security operations assistant', icon: '🤖', type: 'chat', samples: ['What are the current open incidents?', 'Which properties need attention right now?', 'Summarize the security status across all buildings'] },
  { key: 'incident-summarizer', name: 'Incident Summarizer', description: 'AI-powered incident analysis and summaries', icon: '📋', type: 'action', samples: ['Summarize all critical incidents', 'Find patterns in recent security events', 'What are the top priorities for resolution?'] },
  { key: 'anomaly-detection', name: 'Anomaly Detection', description: 'Detect unusual access patterns and behaviors', icon: '🔍', type: 'action', samples: ['Find off-hours access anomalies', 'Detect repeated denied access attempts', 'Identify unusual badge usage patterns'] },
  { key: 'visitor-risk', name: 'Visitor Risk Assessment', description: 'AI risk scoring for visitor management', icon: '⚠️', type: 'action', samples: ['Assess risk for all current visitors', 'Flag visitors at high-incident properties', 'Review unverified visitor IDs'] },
  { key: 'nl-reporting', name: 'Natural Language Reports', description: 'Ask questions in plain English about your data', icon: '💬', type: 'input', samples: ['How many denied access events occurred?', 'Which property has the most cameras?', 'List all guards on night shift'] },
  { key: 'compliance-report', name: 'Compliance Report', description: 'Generate SOC 2 and HIPAA compliance reports', icon: '📊', type: 'action', samples: ['Generate SOC 2 compliance report', 'HIPAA compliance assessment', 'Identify compliance gaps and risks'] },
  { key: 'predictive-maintenance', name: 'Predictive Maintenance', description: 'Predict equipment failures before they happen', icon: '🔧', type: 'action', samples: ['Which cameras are likely to fail soon?', 'Predict upcoming maintenance needs', 'Analyze work order patterns'] },
  { key: 'threat-assessment', name: 'Threat Assessment', description: 'Property security scoring and vulnerability analysis', icon: '🎯', type: 'action', samples: ['Assess threats for One World Trade Center', 'Overall portfolio security score', 'Identify most vulnerable properties'] },
  { key: 'access-pattern-analysis', name: 'Access Pattern Analysis', description: 'Traffic flow and utilization insights', icon: '📈', type: 'action', samples: ['Analyze peak access hours', 'Door utilization report', 'Traffic flow optimization suggestions'] },
  { key: 'smart-scheduling', name: 'Smart Scheduling', description: 'AI-optimized guard shift recommendations', icon: '📅', type: 'action', samples: ['Optimize guard shifts for all properties', 'Night coverage recommendations', 'Balance shifts by risk level'] },
  { key: 'device-health-advisor', name: 'Device Health Advisor', description: 'Flag devices heading toward failure with proactive recommendations', icon: '🩺', type: 'action', samples: ['Which devices are at risk of failure?', 'Explain declining health scores', 'Recommend proactive maintenance actions'] },
  { key: 'firmware-risk-analyzer', name: 'Firmware Risk Analyzer', description: 'Prioritize firmware updates by CVE exposure and criticality', icon: '🛡️', type: 'action', samples: ['Which devices have critical vulnerabilities?', 'Why did firmware updates fail?', 'Recommend firmware rollout priority'] },
  { key: 'network-health-diagnostics', name: 'Network Health Diagnostics', description: 'Identify subnet bottlenecks, single points of failure, and offline chains', icon: '🌐', type: 'action', samples: ['Find single points of failure', 'Which subnets have degraded connections?', 'Recommend network improvements'] },
  { key: 'device-copilot', name: 'Device Intelligence Copilot', description: 'Chat with an AI hardware infrastructure assistant', icon: '🔧', type: 'chat', samples: ['Why did the firmware update fail on RDR-WTC-001?', 'Which property has the worst device health?', 'Summarize all offline devices and their impact'] },
];
